### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by dargmuesli** [FG-Team/FG-App#10]
Wir brauchen 'nen Server. Wie?

Früher oder später.

**Comment by dargmuesli** [comment]
Ich habe ja jetzt einen Raspberry Pi (2 b), ist geplant, dass der immer online ist.
Ist halt privat und unverschlüsselt.
Vielleicht kann man aber auch MD5 oder so benutzen :)

**Comment by muellerius** [comment]
Möglich, aber ich würde da eher auf Software zurückgreifen. Gibt es doch
alles schon...

**Comment by dargmuesli** [comment]
Welche Software meinst du da?

**Comment by muellerius** [comment]
Weiß nicht, aber Software zur Datenbankverwaltung von Accounts gibt es
sicherlich...

**Comment by dargmuesli** [comment]
Ja, das ist klar. Aber von wo soll die Datenbank denn abgerufen werden, wenn nicht von einem Server?

**Comment by muellerius** [comment]
Na holt man sich nen Server mit command Line und installiert sie nötige
Software :b

**Comment by dargmuesli** [comment]
Ach du meinst, auf dem Raspberry soll die Software laufen.
Du meinst kein MD5 sondern eine Datenbank-Software. Ich dachte du meinst keinen Server sondern eine Datenbanksoftware, lol
Und MD5 ist eine kryptografische Hashfunktion, die man am besten mit einer Datenbank benutzt. Sonst könnte sich ja der Admin hinsetzen und sich alle Passwörter anschauen #Verschlüsselung ...

**Comment by muellerius** [comment]
Nein nicht direkt. Also zur Acccount-Verwaltung würde ich auf etwas professionelles zurückgreifen. Halt eine Account-Datenbankverwaltungssoftware. Das muss sein.

**Comment by muellerius** [comment]
Die dann aber auch auf über ne SSL Verbindung zugreift

**Comment by dargmuesli** [comment]
Das wird etwas kosten... Aber die Schule hat ja genug Geld (bzw. die SV) für SSL :D

**Comment by muellerius** [comment]
Jaa. Ich würde die erstmal anschreiben, ob die uns eine Ermäßigung oder ob die das ganze gratis machen...

**Comment by muellerius** [comment]
Also die Hoster
